# Generated by Django 4.2.4 on 2023-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('check_status', models.BooleanField(default=False)),
                ('due_data', models.DateField()),
            ],
        ),
    ]
